ci: add PR test report
Now the PR should include a test report that contains the information
from all the tests we execute

diff --git a/.github/workflows/action.yml b/.github/workflows/action.yml
--- a/.github/workflows/action.yml
+++ b/.github/workflows/action.yml
@@ -45,11 +45,14 @@ jobs:
       # workaround for https://github.com/bazel-contrib/setup-bazel/issues/108
       # together with our customized default_test_runner
       run: cat ~/.bazelrc | grep -v output_base > ~/.bazelrc.clean
+      if: success() || failure() # always run even if the previous step fails
     - id: e2e-that-should-pass
       name: running mandatory e2e tests
       run: bazelisk test e2e --notest_keep_going
+      if: success() || failure() # always run even if the previous step fails
     - id: e2e-that-are-allowed-to-fail
       name: running e2e tests that are allowed to fail
+      if: success() || failure() # always run even if the previous step fails
       run: |
         ret_code=0
         bazel test //e2e --notest_keep_going --test_tag_filters=allowed-to-fail || ret_code=$?
@@ -59,3 +62,8 @@ jobs:
           4) echo "No tests matched the allowed-to-fail filter." ;;
           *) exit $ret_code ;;
         esac
+    - uses: actions/upload-artifact@v4  # upload test results
+      if: success() || failure() # always run even if the previous step fails
+      with:
+        name: test-results
+        path: 'bazel-testlogs/**/test.xml'
