ci: use new e2e setup
Drive tests entirely through bazel even on CI.

Given we're using setup-bazel in our CI we need a little of a workaround
for a bug

diff --git a/.github/workflows/action.yml b/.github/workflows/action.yml
--- a/.github/workflows/action.yml
+++ b/.github/workflows/action.yml
@@ -17,8 +17,8 @@ jobs:
   build-and-test:
     runs-on: ubuntu-latest
     steps:
-    - uses: actions/checkout@v4
-    - uses: bazel-contrib/setup-bazel@0.8.5
+    - uses: actions/checkout@v6.0.2
+    - uses: bazel-contrib/setup-bazel@0.18.0
       with:
         # Avoid downloading Bazel every time.
         bazelisk-cache: true
@@ -34,155 +34,23 @@ jobs:
           try-import %workspace%/../../.github/workflows/ci.bazelrc
         # keep a cache for MODULE.bazel repos
         external-cache: true
-    - run: bazelisk build //... && bazelisk test //...
-
-  e2e-workspace-matrix:
-    strategy:
-      matrix:
-        version:
-          - version: 6.x
-            bazelrc: |
-              import %workspace%/../../.aspect/bazelrc/bazel6.bazelrc
-          - version: 7.x
-            bazelrc: |
-              import %workspace%/../../.aspect/bazelrc/bazel7.bazelrc
-              import %workspace%/../../.aspect/bazelrc/bazel6.bazelrc
-    runs-on: ubuntu-latest
-    steps:
-    - uses: actions/checkout@v4
-    - uses: bazel-contrib/setup-bazel@0.8.5
-      with:
-        # Avoid downloading Bazel every time.
-        bazelisk-cache: true
-        # Keep a disk-cache
-        disk-cache: true
-        # Share repository cache between workflows.
-        repository-cache: true
-        # enable some flags for CI
-        bazelrc: |
-          import %workspace%/../../.aspect/bazelrc/ci.bazelrc
-          import %workspace%/../../.github/workflows/ci.bazelrc
-          ${{ matrix.version.bazelrc }}
-    - run: cd e2e/bazel-workspace && USE_BAZEL_VERSION=${{ matrix.version.version }} bazelisk build //...
-
-  e2e-bzlmod-matrix:
-    strategy:
-      matrix:
-        version: [7.x, 8.x]
-        path:
-          - bazel-bzlmod
-          - bazel-bzlmod-lock-file
-
-    runs-on: ubuntu-latest
-    steps:
-    - uses: actions/checkout@v4
-    - uses: bazel-contrib/setup-bazel@0.8.5
-      with:
-        # Avoid downloading Bazel every time.
-        bazelisk-cache: true
-        # Keep a disk-cache
-        disk-cache: true
-        # Share repository cache between workflows.
-        repository-cache: true
-        # enable some flags for CI
-        bazelrc: |
-          import %workspace%/../../.aspect/bazelrc/ci.bazelrc
-          import %workspace%/../../.github/workflows/ci.bazelrc
-    - run: cd e2e/${{ matrix.path }} && USE_BAZEL_VERSION=${{ matrix.version }} bazelisk build //...
-
-  e2e-bzlmod-build-toolchain-matrix:
-    strategy:
-      matrix:
-        version: [7.x, 8.x]
-
-    runs-on: ubuntu-latest
-    steps:
-    - uses: actions/checkout@v4
-    - uses: bazel-contrib/setup-bazel@0.8.5
-      with:
-        # Avoid downloading Bazel every time.
-        bazelisk-cache: true
-        # Keep a disk-cache
-        disk-cache: true
-        # Share repository cache between workflows.
-        repository-cache: true
-        # enable some flags for CI
-        bazelrc: |
-          import %workspace%/../../.aspect/bazelrc/ci.bazelrc
-          import %workspace%/../../.github/workflows/ci.bazelrc
-    - run: cd e2e/bazel-bzlmod-toolchain-from-source && USE_BAZEL_VERSION=${{ matrix.version }} bazelisk build //...
-
-  e2e-repo-yaml:
-    runs-on: ubuntu-latest
-    steps:
-    - uses: actions/checkout@v4
-    - uses: bazel-contrib/setup-bazel@0.8.5
-      with:
-        # Avoid downloading Bazel every time.
-        bazelisk-cache: true
-        # Keep a disk-cache
-        disk-cache: true
-        # Share repository cache between workflows.
-        repository-cache: true
-        # enable some flags for CI
-        bazelrc: |
-          import %workspace%/.aspect/bazelrc/ci.bazelrc
-          import %workspace%/.github/workflows/ci.bazelrc
-    - run: |
-        export USE_BAZEL_VERSION=7.x
-        bazelisk run //cmd -- init --fc 41 --output $(pwd)/repo.yaml
-        bazelisk run //cmd -- fetch --repofile $(pwd)/repo.yaml
-        bazelisk run //cmd -- resolve --repofile $(pwd)/repo.yaml bash
-
-  e2e-bzlmod-lock-file-from-args:
-    runs-on: ubuntu-latest
-    steps:
-    - uses: actions/checkout@v4
-    - uses: bazel-contrib/setup-bazel@0.8.5
-      with:
-        # Avoid downloading Bazel every time.
-        bazelisk-cache: true
-        # Keep a disk-cache
-        disk-cache: true
-        # Share repository cache between workflows.
-        repository-cache: true
-        # enable some flags for CI
-        bazelrc: |
-          import %workspace%/../../.aspect/bazelrc/ci.bazelrc
-          import %workspace%/../../.github/workflows/ci.bazelrc
-    - run: |
-        export USE_BAZEL_VERSION=8.x
-        cd e2e/bazel-bzlmod-lock-file-from-args && bazelisk run :bazeldnf -- fetch && bazelisk run @bazeldnf_rpms//:update-lock-file && bazelisk build ...
-
-  e2e-bzlmod-toolchain-circular-dependencies:
-    runs-on: ubuntu-latest
-    steps:
-    - uses: actions/checkout@v4
-    - uses: bazel-contrib/setup-bazel@0.8.5
-      with:
-        # Avoid downloading Bazel every time.
-        bazelisk-cache: true
-        # Keep a disk-cache
-        disk-cache: true
-        # Share repository cache between workflows.
-        repository-cache: true
-        # enable some flags for CI
-        bazelrc: |
-          import %workspace%/../../.aspect/bazelrc/ci.bazelrc
-          import %workspace%/../../.github/workflows/ci.bazelrc
-    - id: prepare
+    - id: build
+      run: bazelisk build //...
+    - id: unit-tests
+      run: bazelisk test //...
+    - id: prepare-e2e-runner
+      # workaround for https://github.com/bazel-contrib/setup-bazel/issues/108
+      # together with our customized default_test_runner
+      run: cat ~/.bazelrc | grep -v output_base > ~/.bazelrc.clean
+    - id: e2e-that-should-pass
+      run: bazelisk test e2e --notest_keep_going
+    - id: e2e-that-are-allowed-to-fail
       run: |
-        export USE_BAZEL_VERSION=8.x
-        cd e2e/bzlmod-toolchain-circular-dependencies
-        bazelisk run @bazeldnf_rpms//:fetch-repo
-        bazelisk run @bazeldnf_rpms//:update-lock-file
-    - id: test
-      run: |
-        export USE_BAZEL_VERSION=8.x
-        cd e2e/bzlmod-toolchain-circular-dependencies
-        bazelisk build //... || status=$?
-        if [ ${status} -ne 0 ]; then
-          echo "::warning::Optional job failed."
-          echo "optional_fail=true" >> "${GITHUB_OUTPUT}"
-          echo "optional_fail_status=${status}" >> "${GITHUB_OUTPUT}"
-        fi
+        ret_code=0
+        bazel test //e2e --notest_keep_going --test_tag_filters=allowed-to-fail || ret_code=$?
+        case $ret_code in
+          0) echo "All allowed-to-fail tests passed." ;;
+          3) echo "::warning::Some allowed-to-fail e2e tests failed or timed out." ;;
+          4) echo "No tests matched the allowed-to-fail filter." ;;
+          *) exit $ret_code ;;
+        esac
